version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  front:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    command: bash -c 'composer install --prefer-source --no-interaction && php artisan serve --host 0.0.0.0 --port 80'
    environment:
      - "VIRTUAL_HOST=local.laravel.rad"
    working_dir: /var/www
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - vendor:/var/www/vendor
    env_file: .env

  mysql:
      image: mysql:5.7.18
      environment:
          - "MYSQL_ROOT_PASSWORD=RootPasswd"
          - "MYSQL_DATABASE=homestead"
          - "MYSQL_USER=homestead"
          - "MYSQL_PASSWORD=secret"
      ports:
          - "3306:3306"
      volumes:
        - ./docker/mysql-initdb:/docker-entrypoint-initdb.d
        - dbdata:/var/lib/mysql

volumes:
  dbdata:
  vendor:
  ws_nodemodules:
